<?php

return [

    'itemType' => [
        -1 => 'Undocumented',
        0 => '-',
        1 => 'Weapon',
        2 => 'Armor',
        3 => 'Consumable',
        4 => 'Ammo',
        5 => 'Etc',
        6 => 'Card',
        7 => 'Cash',
        9 => 'Shadow Weapon',
        10 => 'Shadow Armor',
    ],

    'subTypes' => [
        -1 => 'Undocumented',
        0 => '-',
        256 => 'Dagger',
        257 => 'Sword',
        258 => 'Two-handed Sword',
        259 => 'Spear',
        260 => 'Two-handed Spear',
        261 => 'Axe',
        262 => 'Two-handed Axe',
        263 => 'Mace',
        265 => 'Rod',
        266 => 'Two-handed Rod',
        267 => 'Bow',
        268 => 'Fist Weapon',
        269 => 'Instrument',
        270 => 'Whip',
        271 => 'Book',
        272 => 'Katar',
        273 => 'Pistol',
        274 => 'Rifle',
        275 => 'Gatling Gun',
        276 => 'Shotgun',
        277 => 'Grenade Launcher',
        278 => 'Shuriken',
        280 => 'Shadow Weapon',
        512 => 'Helm',
        513 => 'Armor',
        514 => 'Shield',
        515 => 'Garment',
        516 => 'Shoes',
        517 => 'Accessory',
        518 => 'Pet',
        519 => 'Costume Helm',
        522 => 'Costume Garment',
        526 => 'Shadow Armor',
        527 => 'Shadow Shield',
        528 => 'Shadow Shoes',
        529 => 'Shadow Acc. (Right)',
        530 => 'Shadow Acc. (Left)',
        531 => 'Shadow Accessory',
        768 => 'Special',
        769 => 'Regeneration',
        102 =>  'Arrow',
        1025 =>  'Cannonball',
        1026 =>  'Throw Weapon',
        1027 =>  'Ammo',
        1028 =>  'Taming item',
    ],

];
